[workspace]
members = [".", "crates/bargo-core"]

[package]
name = "bargo"
version = "0.1.0"
edition = "2024"

[dependencies]
bargo-core = { path = "crates/bargo-core" }
color-eyre = "0.6.5"

[dev-dependencies]
tempfile = "3.8"
assert_cmd = "2"
predicates = "3"
serde_json = "1.0"
